Update docs - Email survey API
Wootric/slate pull request #93
Opened 2018-12-01 00:43 UTC by marinhero

- Add docs to reference the new sampling override feature

Trello:
https://trello.com/c/5UAq7b1d/4002-15-allow-survey-sampling-configuration-via-email-api-1

2018-12-01 06:47 UTC, hachibu requested changes

2018-12-01 06:47 UTC, hachibu commented on source/includes/_email_survey.md
> +You may use this parameters to overwrite the settings you have in your Wootric settings panel
```suggestion
You may use these parameters to overwrite the settings you have in your Wootric settings panel.
```

2018-12-01 06:47 UTC, hachibu commented on source/includes/_email_survey.md
> +first_survey_delay | Integer |Number of days that have to pass since end_user's created_at to show a survey
```suggestion
first_survey_delay | Integer | Number of days that have to pass since end user's created_at to show a survey
```

2018-12-03 23:50 UTC, marinhero commented
Updated and rebases @hachibu. Ready for another 👁

2018-12-04 20:38 UTC, hachibu approved these changes
Ship!

2018-12-04 20:39 UTC, marinhero commented
Thanks Ray!

2018-12-04 20:40 UTC, merged